
service: anomalies-detector
frameworkVersion: '3'

custom:
  classificationResultsTableName: 'java-classifications-${self:provider.stage}'
  authorizerARN: 'UserPoolARN'
  logGroupName: 'PROD-Logs'
  openaiKey: 'openAIKey'
  retrievalMinutes: '5'
  limitEvents: '10'
  openaiTimeout: '120'
  openaiMaxTokens: '360'

provider:
  name: aws
  runtime: java8
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    CLASSIFICATIONS_TABLE_NAME: ${self:custom.classificationResultsTableName}
    LOG_GROUP_NAME: ${self:custom.logGroupName}
    OPEN_AI_API_KEY: ${self:custom.openaiKey}
    RETRIEVAL_MINUTES: ${self:custom.retrievalMinutes}
    LIMIT_EVENTS: ${self:custom.limitEvents}
    OPEN_AI_TIMEOUT: ${self:custom.openaiTimeout}
    OPEN_AI_MAX_TOKENS: ${self:custom.openaiMaxTokens}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": [ "ClassificationsDynamoDBTable", "Arn" ] }

    - Effect: Allow
      Action:
        - logs:FilterLogEvents
      Resource: '*'

package:
  artifact: 'target/${self:service}-${self:provider.stage}.jar'


functions:
  processLogs:
    handler: com.serverless.services.ProcessLogs
    timeout: 30
    events:
      - http:
          path: /logs
          method: get
          cors: true
          authorizer:
            arn: ${self:custom.authorizerARN}
  getLogs:
    handler: com.serverless.services.ListLogs
    timeout: 30
    events:
      - http:
          path: /logs/getAll
          method: get
          cors: true
          authorizer:
            arn: ${self:custom.authorizerARN}
resources:
  Resources:
    ClassificationsDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.classificationResultsTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1